.Dd October 23, 2008
.Dt PWS_PASSWORDS_CONVERTTOMULTI 3
.Os
.Sh NAME
.Nm pws_passwords_converttomulti
.Nd Convert an encoded password string to a PasswordData object
.Sh LIBRARY
-lpwstor
.Sh SYNOPSIS
.In pwstor.h
.Ft int
.Fo pws_passwords_converttomulti
.Fa "unsigned char *indata"
.Fa "PasswordData *outdata"
.Fa "uint8_t is_b64"
.Fc
.Sh DESCRIPTION
The 
.Fn pws_passwords_converttomulti 
function converts a password string to a 
.Fa "PasswordData" 
structure.  A pointer to valid memory large enough to hold the result must be passed to the function as 
.Fa outdata .  
The 
.Fa indata 
argument should contain valid password data.  If the 
.Fa is_b64 
argument is true, the data contained in 
.Fa indata 
must be Base64 encoded.  If it is false, the data in 
.Fa indata 
must not be Base64 encoded.  
.Pp
This function will return zero indicating success, or non-zero indicating failure.  
.Sh SEE ALSO
.Xr pwstor 3
.Xr pws_passwords_encode 3 ,
.Xr pws_passwords_encodemulti 3 ,
.Xr pws_passwords_check 3 ,
.Xr pws_passwords_checkmulti 3
